# Name: Shrook Ehab Attia

# Group No. : 1

# Lecturer Name: DR. Randa

In [99]:
import numpy as np

# Question 1: 
### Implement the function S = IsSquare(A) that checks the dimension of input matrix A, and returns 1 if the input matrix is square and 0 otherwise.

In [100]:
def IsSquare(A):
    noOfRows = len(A)
    for row in A:
        if len(row) != noOfRows:
            return 0 #matrix is not square
        return 1 #matrix is square
    
a = np.array([[2.0,2.0],[2.0,1.0],[5.0,5.0]], dtype=np.float64)
print('==========3x2 Matrix============')
print('Matrix A: ')
print(a)
print('The dimension of Matrix A is Square?: ', IsSquare(a))
print('*********************************')
print('==========2x2 Matrix============')
a = np.array([[2.0,2.0],[5.0,5.0]], dtype=np.float64)
print('Matrix A: ')
print(a)
print('The dimension of Matrix A is Square?: ', IsSquare(a))

==========3x2 Matrix============
Matrix A: 
[[2. 2.]
 [2. 1.]
 [5. 5.]]
The dimension of Matrix A is Square?:  0
*********************************
==========2x2 Matrix============
Matrix A: 
[[2. 2.]
 [5. 5.]]
The dimension of Matrix A is Square?:  1


# Question 2: 
### Implement the function N = Props(A) that checks the properties of the input matrix A:

 ### 2.1. checks the input matrix is square.

### 2.2. computes the matrix rank, prints the rank value (hint: use numpy method).

### 2.3. computes the matrix determinant (hint: use numpy method) and prints its value.

### 2.4. returns 1 if the input matrix has rank = no. of rows in matrix A and 0 otherwise.

In [101]:
def Props(A):
    if IsSquare(A):
        print("The Matrix is Square")
        print('Matrix Determinant = ', np.linalg.det(A))
        
    else:
        print("The Matrix is not Square")
    rank = np.linalg.matrix_rank(A)
    print('Matrix Rank = ', rank)
    noOfRows = len(A)
    if noOfRows == rank:
        return 1 #matrix has rank = no. of rows in matrix A
    return 0

a = np.array([[2.0,2.0],[5.0,5.0]], dtype=np.float64)
print('Matrix A: ')
print(a)
print('*********************************')
print('==========Matrix Properties============')
print('If The Rank = The Number of Rows?: ', Props(a))
print('*********************************')
a = np.array([[2.0,2.0],[2.0,1.0],[5.0,5.0]], dtype=np.float64)
print('Matrix A: ')
print(a)
print('*********************************')
print('==========Matrix Properties============')
print('If The Rank = The Number of Rows?: ', Props(a))

Matrix A: 
[[2. 2.]
 [5. 5.]]
*********************************
==========Matrix Properties============
The Matrix is Square
Matrix Determinant =  5.551115123125802e-16
Matrix Rank =  1
If The Rank = The Number of Rows?:  0
*********************************
Matrix A: 
[[2. 2.]
 [2. 1.]
 [5. 5.]]
*********************************
==========Matrix Properties============
The Matrix is not Square
Matrix Rank =  2
If The Rank = The Number of Rows?:  0


# Question 3:
### Compose the equations corresponding to the two word-problems below and put them in matrix-vector form AX = B. Call "Props" to find more about their properties.

### 1-Compute AX = B (for System 1):

In [102]:
A = np.array([[1.5,5.75,2.6], [1,1,1], [0,1,-1]], dtype=np.float64)
B = np.array([[589.5],[200],[-20]], dtype=np.float64)
X = np.dot(np.linalg.inv(A), B) 
print('Matrix A: ')
print(A)
print('==========Matrix Properties============')
print('If The Rank = The Number of Rows?: ', Props(A))
print('*********************************')
print('Matrix B: ')
print(B)
print('==========Matrix Properties============')
print('If The Rank = The Number of Rows?: ', Props(B))
print('*********************************')
if np.linalg.det(A) == 0:
    print('X is A Singular matrix!!')
else:
    X = np.dot(np.linalg.inv(A), B) 
    print('Matrix X: ')
    print(X)
    print('==========Matrix Properties============')
    print('If The Rank = The Number of Rows?: ', Props(X))

Matrix A: 
[[ 1.5   5.75  2.6 ]
 [ 1.    1.    1.  ]
 [ 0.    1.   -1.  ]]
==========Matrix Properties============
The Matrix is Square
Matrix Determinant =  5.35
Matrix Rank =  3
If The Rank = The Number of Rows?:  1
*********************************
Matrix B: 
[[589.5]
 [200. ]
 [-20. ]]
==========Matrix Properties============
The Matrix is not Square
Matrix Rank =  1
If The Rank = The Number of Rows?:  0
*********************************
Matrix X: 
[[80.]
 [50.]
 [70.]]
==========Matrix Properties============
The Matrix is not Square
Matrix Rank =  1
If The Rank = The Number of Rows?:  0


### 2-Compute AX = B (for System 2):

In [103]:
A = np.array([[2,1,-3], [4,2,-6], [1,-1,1]], dtype=np.float64)
B = np.array([[0],[0],[0]], dtype=np.float64)
print('Matrix A: ')
print(A)
print('==========Matrix Properties============')
print('If The Rank = The Number of Rows?: ', Props(A))
print('*********************************')
print('Matrix B: ')
print(B)
print('==========Matrix Properties============')
print('If The Rank = The Number of Rows?: ', Props(B))
print('*********************************')
if np.linalg.det(A) == 0: #if det(A)=0 then A is not invertible 
    print('X is A Singular matrix!!')
else:
    X = np.dot(np.linalg.inv(A), B) 
    print('Matrix X: ')
    print(X)
    print('==========Matrix Properties============')
    print('If The Rank = The Number of Rows?: ', Props(X))

Matrix A: 
[[ 2.  1. -3.]
 [ 4.  2. -6.]
 [ 1. -1.  1.]]
==========Matrix Properties============
The Matrix is Square
Matrix Determinant =  0.0
Matrix Rank =  2
If The Rank = The Number of Rows?:  0
*********************************
Matrix B: 
[[0.]
 [0.]
 [0.]]
==========Matrix Properties============
The Matrix is not Square
Matrix Rank =  0
If The Rank = The Number of Rows?:  0
*********************************
X is A Singular matrix!!


# Question 4:
###  Implement the function reducerow(C,pivotrow,targetrow,pivot):

### 4.1. Takes an input matrix C, index of a pivot row vector, index of a target row vector, index of a pivot element. It returns nothing but overrides the matrix C.
### 4.2. Checks if the pivot element = 1 otherwise perform vector operation to make it = 1.
### 4.3. Uses vector operations using the two vectors “pivotrow” & “targetrow” to make the element corresponding to the pivot element in the targetrow vector = 0.

In [104]:
def reducerow(C, pivotrow, targetrow, pivot):
    if C[pivotrow, pivot] != 0 and C[pivotrow, pivot] != 1: #Check for pivot is not equal to 1 or zero as we can't divide by zero
        C[pivotrow] = C[pivotrow] / C[pivotrow, pivot]
    if C[targetrow, pivot] !=0: #check that the targetrow is not already zero to minimize the no. of steps
        C[targetrow] = C[targetrow] - C[targetrow, pivot] * C[pivotrow]

C = np.array([[2,-1,-6],[-2,1,2],[3,-4,2]], dtype=np.float64)
print("Matrix C before Applying RREF: ")
print(C)
reducerow(C, 0, 2, 0)
print('*********************************')
print("Matrix C after Applying RREF for the first time: ")
print(C)

Matrix C before Applying RREF: 
[[ 2. -1. -6.]
 [-2.  1.  2.]
 [ 3. -4.  2.]]
*********************************
Matrix C after Applying RREF for the first time: 
[[ 1.  -0.5 -3. ]
 [-2.   1.   2. ]
 [ 0.  -2.5 11. ]]


# Question 5:
### Implement the function f = SolveLinearSystem (A,B):
### 5.1. Takes as an input coefficient matrix A and target vector B.
### 5.2. Adjoins A and B then perform row reduction operations using “reducerow” trying to convert it A’s columns into an identity matrix.
### 5.3. returns f = the summation of A’s columns elements after row reduction.

In [105]:
def SolveLinearSystem(A,B):
    C = np.concatenate((A,B), axis = 1)
    C.dtype = 'float64'
    pivot = 0
    for pivotrow in range(A.shape[0]):
        if C[pivotrow][pivot] == 0: #swap the first row that doesn't have a zero in pivot element
            swaprow = C[pivotrow]
            swapedrow = pivotrow + 1
            while swapedrow < A.shape[0]:
                if C[swapedrow][pivot] != 0:
                    C[pivotrow] = C[swapedrow]
                    C[swapedrow] = swaprow
                    break
                else:
                    swapedrow = swapedrow + 1

        targetrows = list(range(A.shape[0])) #list of the rows without pivot row
        del targetrows[pivotrow] # remove pivot row from list

        for targetrow in targetrows:
            reducerow(C, pivotrow, targetrow, pivot) #call reducerow for target row to reach RREF
        pivot = pivot + 1 #go to the next pivot
     
    return (np.sum(C[:,0:A.shape[1]]), C) # return summation of A’s columns elements after row reduction, and Matrix C

A= np.array([[2,0,-6],[0,1,2],[3,6,-2]], dtype = "float64")
B = np.array([[2,-1,-6],[-2,1,2],[3,-4,2]], dtype=np.float64)
print("Matrix A: ")
print(A)
print('*********************************')
print("Matrix B: ")
print(B)
print('*********************************')
summation, C = SolveLinearSystem(A,B)
print("Matrix C After Applying RREF: ")
print(C)
print('*********************************')
print('The Sum of A’s columns elements after row reduction', summation)

Matrix A: 
[[ 2.  0. -6.]
 [ 0.  1.  2.]
 [ 3.  6. -2.]]
*********************************
Matrix B: 
[[ 2. -1. -6.]
 [-2.  1.  2.]
 [ 3. -4.  2.]]
*********************************
Matrix C After Applying RREF: 
[[ 1.   0.   0.  -6.2  4.6 -2.4]
 [ 0.   1.   0.   2.8 -2.4  1.6]
 [-0.  -0.   1.  -2.4  1.7  0.2]]
*********************************
The Sum of A’s columns elements after row reduction 3.0


# Question 6:
### Call “SolveLinearSystem” to solve the systems 1 and 2 you previously created in Q3.

### Applying for System 1:

In [106]:
A = np.array([[1.5,5.75,2.6], [1,1,1], [0,1,-1]], dtype=np.float64)
B = np.array([[589.5],[200],[-20]], dtype=np.float64)
print("Matrix A: ")
print(A)
print('*********************************')
print("Matrix B: ")
print(B)
print('*********************************')
summation, C = SolveLinearSystem(A,B)
print("Matrix C After Applying RREF: ")
print(C)
print('*********************************')
print('The Sum of A’s columns elements after row reduction', summation)

Matrix A: 
[[ 1.5   5.75  2.6 ]
 [ 1.    1.    1.  ]
 [ 0.    1.   -1.  ]]
*********************************
Matrix B: 
[[589.5]
 [200. ]
 [-20. ]]
*********************************
Matrix C After Applying RREF: 
[[ 1.  0.  0. 80.]
 [ 0.  1.  0. 50.]
 [-0. -0.  1. 70.]]
*********************************
The Sum of A’s columns elements after row reduction 3.0


### Applying for System 2:

In [107]:
A = np.array([[2,1,-3], [4,2,-6], [1,-1,1]], dtype=np.float64)
B = np.array([[0],[0],[0]], dtype=np.float64)
print("Matrix A: ")
print(A)
print('*********************************')
print("Matrix B: ")
print(B)
print('*********************************')
summation, C = SolveLinearSystem(A,B)
print("Matrix C After Applying RREF: ")
print(C)
print('*********************************')
print('The Sum of A’s columns elements after row reduction', summation)

Matrix A: 
[[ 2.  1. -3.]
 [ 4.  2. -6.]
 [ 1. -1.  1.]]
*********************************
Matrix B: 
[[0.]
 [0.]
 [0.]]
*********************************
Matrix C After Applying RREF: 
[[ 1.          0.         -0.66666667  0.        ]
 [ 0.          1.         -1.66666667  0.        ]
 [ 0.          0.          0.          0.        ]]
*********************************
The Sum of A’s columns elements after row reduction -0.33333333333333337


# Question 7:
### For system 1: there is a unique solutuion as all varaibles are basic and the output: X = [[x1],[x2],[x3]] = [[80.],[50.],[70.]]
### for system 2: There is no solution as the det(A)=0 then this matrix is invertible.

# Question 8: 
### Type these code lines and check your answers for systems 1 and 2
### 1-using x = np.linalg.solve(A, B) (for system 1)


In [108]:
A = np.array([[1.5,5.75,2.6], [1,1,1], [0,1,-1]], dtype=np.float64)
B = np.array([[589.5],[200],[-20]], dtype=np.float64)
print('Matrix A: ')
print(A)
print('==========Matrix Properties============')
print('If The Rank = The Number of Rows: ', Props(A))
print('*********************************')
print('Matrix B: ')
print(B)
print('==========Matrix Properties============')
print('If The Rank = The Number of Rows: ', Props(B))
print('*********************************')
if np.linalg.det(A) == 0: #if det(A)=0 then A is not invertible 
    print('X is A Singular matrix!!')
else:
    X = np.linalg.solve(A, B) 
    print('Matrix X: ')
    print(X)
    print('==========Matrix Properties============')
    print('If The Rank = The Number of Rows: ', Props(X))

Matrix A: 
[[ 1.5   5.75  2.6 ]
 [ 1.    1.    1.  ]
 [ 0.    1.   -1.  ]]
==========Matrix Properties============
The Matrix is Square
Matrix Determinant =  5.35
Matrix Rank =  3
If The Rank = The Number of Rows:  1
*********************************
Matrix B: 
[[589.5]
 [200. ]
 [-20. ]]
==========Matrix Properties============
The Matrix is not Square
Matrix Rank =  1
If The Rank = The Number of Rows:  0
*********************************
Matrix X: 
[[80.]
 [50.]
 [70.]]
==========Matrix Properties============
The Matrix is not Square
Matrix Rank =  1
If The Rank = The Number of Rows:  0


### 1-using x = np.linalg.solve(A, B) (for system 2)

In [109]:
A = np.array([[2,1,-3], [4,2,-6], [1,-1,1]], dtype=np.float64)
B = np.array([[0],[0],[0]], dtype=np.float64)
print('Matrix A: ')
print(A)
print('==========Matrix Properties============')
print('If The Rank = The Number of Rows: ', Props(A))
print('*********************************')
print('Matrix B: ')
print(B)
print('==========Matrix Properties============')
print('If The Rank = The Number of Rows: ', Props(B))
print('*********************************')
if np.linalg.det(A) == 0: #if det(A)=0 then A is not invertible 
    print('X is A Singular matrix!!')
else:
    X = np.linalg.solve(A, B) 
    print('Matrix X: ')
    print(X)
    print('==========Matrix Properties============')
    print('If The Rank = The Number of Rows: ', Props(X))

Matrix A: 
[[ 2.  1. -3.]
 [ 4.  2. -6.]
 [ 1. -1.  1.]]
==========Matrix Properties============
The Matrix is Square
Matrix Determinant =  0.0
Matrix Rank =  2
If The Rank = The Number of Rows:  0
*********************************
Matrix B: 
[[0.]
 [0.]
 [0.]]
==========Matrix Properties============
The Matrix is not Square
Matrix Rank =  0
If The Rank = The Number of Rows:  0
*********************************
X is A Singular matrix!!


### 2-using np.allclose(np.dot(A, x), B) (for system 1)

In [110]:
A = np.array([[1.5,5.75,2.6], [1,1,1], [0,1,-1]], dtype=np.float64)
B = np.array([[589.5],[200],[-20]], dtype=np.float64)
print('Matrix A: ')
print(A)
print('==========Matrix Properties============')
print('If The Rank = The Number of Rows: ', Props(A))
print('*********************************')
print('Matrix B: ')
print(B)
print('==========Matrix Properties============')
print('If The Rank = The Number of Rows: ', Props(B))
print('*********************************')
if np.linalg.det(A) == 0: #if det(A)=0 then A is not invertible 
    print('X is A Singular matrix!!')
else:
    np.allclose(np.dot(A, X), B)  
    print('Matrix X: ')
    print(X)
    print('==========Matrix Properties============')
    print('If The Rank = The Number of Rows: ', Props(X))

Matrix A: 
[[ 1.5   5.75  2.6 ]
 [ 1.    1.    1.  ]
 [ 0.    1.   -1.  ]]
==========Matrix Properties============
The Matrix is Square
Matrix Determinant =  5.35
Matrix Rank =  3
If The Rank = The Number of Rows:  1
*********************************
Matrix B: 
[[589.5]
 [200. ]
 [-20. ]]
==========Matrix Properties============
The Matrix is not Square
Matrix Rank =  1
If The Rank = The Number of Rows:  0
*********************************
Matrix X: 
[[80.]
 [50.]
 [70.]]
==========Matrix Properties============
The Matrix is not Square
Matrix Rank =  1
If The Rank = The Number of Rows:  0


### 2-using np.allclose(np.dot(A, x), B) (for system 2)

In [111]:
A = np.array([[2,1,-3], [4,2,-6], [1,-1,1]], dtype=np.float64)
B = np.array([[0],[0],[0]], dtype=np.float64)
print('Matrix A: ')
print(A)
print('==========Matrix Properties============')
print('If The Rank = The Number of Rows: ', Props(A))
print('*********************************')
print('Matrix B: ')
print(B)
print('==========Matrix Properties============')
print('If The Rank = The Number of Rows: ', Props(B))
print('*********************************')
if np.linalg.det(A) == 0: #if det(A)=0 then A is not invertible 
    print('X is A Singular matrix!!')
else:
    np.allclose(np.dot(A, X), B) 
    print('Matrix X: ')
    print(X)
    print('==========Matrix Properties============')
    print('If The Rank = The Number of Rows: ', Props(X))

Matrix A: 
[[ 2.  1. -3.]
 [ 4.  2. -6.]
 [ 1. -1.  1.]]
==========Matrix Properties============
The Matrix is Square
Matrix Determinant =  0.0
Matrix Rank =  2
If The Rank = The Number of Rows:  0
*********************************
Matrix B: 
[[0.]
 [0.]
 [0.]]
==========Matrix Properties============
The Matrix is not Square
Matrix Rank =  0
If The Rank = The Number of Rows:  0
*********************************
X is A Singular matrix!!


# Question 9:
### Call the same function “SolveLinearSystem” to get inv(A) for systems 1 and 2
### 1- using SolveLinearSystem(A,I) to get inv(A) (for systems 1) 


In [112]:
A = np.array([[1.5,5.75,2.6], [1,1,1], [0,1,-1]], dtype=np.float64)
B = np.array([[1,0,0], [0,1,0], [0,0,1]], dtype=np.float64)
print("Matrix A: ")
print(A)
print('*********************************')
print("Matrix B: ")
print(B)
print('*********************************')
summation, C = SolveLinearSystem(A,B)
print("Inverse Matrix of A: ")
print(C)
print('*********************************')
print('The Sum of A’s columns elements after row reduction', summation)

Matrix A: 
[[ 1.5   5.75  2.6 ]
 [ 1.    1.    1.  ]
 [ 0.    1.   -1.  ]]
*********************************
Matrix B: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
*********************************
Inverse Matrix of A: 
[[ 1.          0.          0.         -0.37383178  1.56074766  0.58878505]
 [ 0.          1.          0.          0.18691589 -0.28037383  0.20560748]
 [-0.         -0.          1.          0.18691589 -0.28037383 -0.79439252]]
*********************************
The Sum of A’s columns elements after row reduction 3.0


### 2- using SolveLinearSystem(A,I) to get inv(A) (for systems 2) 
#### This has no inverse since det(A)=0

In [113]:
A = np.array([[2,1,-3], [4,2,-6], [1,-1,1]], dtype=np.float64)
B = np.array([[1,0,0], [0,1,0], [0,0,1]], dtype=np.float64)
print("Matrix A: ")
print(A)
print('*********************************')
print("Matrix B: ")
print(B)
print('*********************************')
summation, C = SolveLinearSystem(A,B)
print("Inverse Matrix of A: ")
print(C)
print('*********************************')
print('The Sum of A’s columns elements after row reduction', summation)

Matrix A: 
[[ 2.  1. -3.]
 [ 4.  2. -6.]
 [ 1. -1.  1.]]
*********************************
Matrix B: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
*********************************
Inverse Matrix of A: 
[[ 1.          0.         -0.66666667  0.33333333  0.          0.33333333]
 [ 0.          1.         -1.66666667  0.33333333  0.         -0.66666667]
 [ 0.          0.          0.          0.          0.          0.        ]]
*********************************
The Sum of A’s columns elements after row reduction -0.33333333333333337


# Question 10:

### 1- using np.linalg.inv(A) to get inv(A) (for systems 1) 

In [114]:
A = np.array([[1.5,5.75,2.6], [1,1,1], [0,1,-1]], dtype=np.float64)
B = np.array([[1,0,0], [0,1,0], [0,0,1]], dtype=np.float64)
print("Matrix A: ")
print(A)
print('*********************************')
print("Matrix B: ")
print(B)
print('*********************************')
print('Inverse Matrix of A: ', np.linalg.inv(A))

Matrix A: 
[[ 1.5   5.75  2.6 ]
 [ 1.    1.    1.  ]
 [ 0.    1.   -1.  ]]
*********************************
Matrix B: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
*********************************
Inverse Matrix of A:  [[-0.37383178  1.56074766  0.58878505]
 [ 0.18691589 -0.28037383  0.20560748]
 [ 0.18691589 -0.28037383 -0.79439252]]


### 2- using np.linalg.inv(A) to get inv(A) (for systems 2) 
#### This has no inverse since det(A)=0

In [115]:
A = np.array([[2,1,-3], [4,2,-6], [1,-1,1]], dtype=np.float64)
B = np.array([[1,0,0], [0,1,0], [0,0,1]], dtype=np.float64)
print("Matrix A: ")
print(A)
print('*********************************')
print("Matrix B: ")
print(B)
print('*********************************')
print('Inverse Matrix of A: ', np.linalg.inv(A))

Matrix A: 
[[ 2.  1. -3.]
 [ 4.  2. -6.]
 [ 1. -1.  1.]]
*********************************
Matrix B: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
*********************************


LinAlgError: Singular matrix